---
- ignore: {name: "Redundant do", within: spec}
- ignore: {name: "Eta reduce"}
- ignore: {name: "Use list comprehension"}
- ignore: {name: "Reduce duplication"}
- ignore: {name: "Avoid restricted qualification", within: Faktory.Prelude}

# Custom Warnings
- warn: {lhs: fromJust, rhs: fromJustNote}
- warn: {lhs: mapM, rhs: traverse}
- warn: {lhs: mapM_, rhs: traverse_}
- warn: {lhs: forM, rhs: for}
- warn: {lhs: forM_, rhs: for_}

# Specify additional command line arguments
- arguments:
  - -XBangPatterns
  - -XDeriveAnyClass
  - -XDeriveFoldable
  - -XDeriveFunctor
  - -XDeriveGeneric
  - -XDeriveLift
  - -XDeriveTraversable
  - -XDerivingStrategies
  - -XFlexibleContexts
  - -XFlexibleInstances
  - -XGADTs
  - -XGeneralizedNewtypeDeriving
  - -XLambdaCase
  - -XMultiParamTypeClasses
  - -XNoImplicitPrelude
  - -XNoMonomorphismRestriction
  - -XOverloadedStrings
  - -XRankNTypes
  - -XRecordWildCards
  - -XScopedTypeVariables
  - -XStandaloneDeriving
  - -XTypeApplications
  - -XTypeFamilies

- modules:
  - {name: [Data.Set], as: Set}
  - {name: [Data.Map], as: Map}
  - {name: [Data.HashSet], as: HashSet}
  - {name: [Data.HashMap.Strict], as: HashMap}
  - {name: [Data.Text], as: T}
  - {name: [Data.Text.Encoding], as: T}
  - {name: [Data.Text.IO], as: T}
  - {name: [Data.Text.Lazy], as: TL}
  - {name: [Data.Text.Lazy.Encoding], as: TL}
  - {name: [Data.Text.IO.Lazy], as: TL}
  - {name: [Data.ByteString], as: BS}
  - {name: [Data.ByteString.Lazy], as: BSL}
  - {name: [Data.ByteString.Char8], as: BS8}
  - {name: [Data.ByteString.Lazy.Char8], as: BSL8}
  - {name: [Data.List.NonEmpty], as: NE}
  - {name: [Data.Sequence], as: Seq}

- functions:
  - {name: unsafePerformIO, within: []}  # never use unsafePerformIO
  - {name: fromJustNote, within: []}  # cause warning on fromJustNote
