---
name: faktory
version: 1.0.0.0
category: Network
author: Freckle Engineering
maintainer: engineering@freckle.com
copyright: 2018 Freckle Education
license: MIT
github: frontrowed/faktory_worker_haskell
synopsis: Faktory Worker for Haskell
description: |
  Haskell client and worker process for the Faktory background job server.

  == Architecture overview

  @
  |                        +--------------------+
  |                        |                    |
  |                        |     Faktory        |
  |                        |     Server         |
  |         +---------->>>>|                    +>>>>--------+
  |         |              |                    |            |
  |         |              |                    |            |
  |         |              +--------------------+            |
  | +-----------------+                            +-------------------+
  | |                 |                            |                   |
  | |    Client       |                            |     Worker        |
  | |    pushes       |                            |     pulls         |
  | |     jobs        |                            |      jobs         |
  | |                 |                            |                   |
  | |                 |                            |                   |
  | +-----------------+                            +-------------------+
  @

  * `Client` - an API any process can use to push jobs to the Faktory server.
  * `Worker` - a process that pulls jobs from Faktory and executes them.
  * `Server` - the Faktory daemon which stores background jobs in queues to be processed by Workers.

  This package contains only the `Client` and `Worker`.

extra-doc-files:
  - CHANGELOG.md
  - README.lhs

tested-with:
  - GHC==8.4.4
  - GHC==8.6.3

ghc-options:
  -Weverything
  -Wno-missing-exported-signatures
  -Wno-missed-specialisations
  -Wno-all-missed-specialisations
  -Wno-unsafe
  -Wno-safe
  -Wno-missing-local-signatures
  -Wno-monomorphism-restriction
  -Wno-missing-import-lists

dependencies:
  - base >= 4.11 && < 5

default-extensions:
  - BangPatterns
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies

library:
  source-dirs: library
  dependencies:
    - aeson >= 1.3 && < 2
    - aeson-casing >= 0.1 && < 1
    - bytestring >= 0.1 && < 1
    - connection >= 0.2 && < 1
    - cryptonite >= 0.2 && < 1
    - megaparsec >= 7 && < 8
    - memory >= 0.1 && < 1
    - network >= 2.6 && < 3
    - random >= 1.1 && < 2
    - safe-exceptions >= 0.1 && < 1
    - scanner >= 0.2 && < 1
    - text >= 1.2 && < 2
    - time >= 1.8 && < 2
    - unix >= 2.7 && < 3

executables:
  faktory-example-producer:
    main: Main.hs
    source-dirs: examples/producer
    dependencies:
      - aeson
      - faktory
      - safe-exceptions

  faktory-example-consumer:
    main: Main.hs
    source-dirs: examples/consumer
    dependencies:
      - aeson
      - faktory
      - safe-exceptions

tests:
  hspec:
    main: Spec.hs
    source-dirs: tests
    ghc-options: -rtsopts
    dependencies:
      - faktory
      - hspec

  readme:
    main: README.lhs
    source-dirs: .
    ghc-options: -pgmL markdown-unlit
    dependencies:
      - aeson
      - base
      - faktory
      - markdown-unlit
