---
name: faktory
version: 0.1.0.0
category: Network
author: Pat Brisbin
maintainer: pbrisbin@freckle.com
copyright: 2018 Freckle Education
license: MIT
github: frontrowed/faktory_worker_haskell
synopsis: Faktory Worker for Haskell
description: |
  Haskell client and worker process for the Faktory background job server.

  == Architecture overview

  @
  |                        +--------------------+
  |                        |                    |
  |                        |     Faktory        |
  |                        |     Server         |
  |         +---------->>>>|                    +>>>>--------+
  |         |              |                    |            |
  |         |              |                    |            |
  |         |              +--------------------+            |
  | +-----------------+                            +-------------------+
  | |                 |                            |                   |
  | |    Client       |                            |     Worker        |
  | |    pushes       |                            |     pulls         |
  | |     jobs        |                            |      jobs         |
  | |                 |                            |                   |
  | |                 |                            |                   |
  | +-----------------+                            +-------------------+
  @

  * `Client` - an API any process can use to push jobs to the Faktory server.
  * `Worker` - a process that pulls jobs from Faktory and executes them.
  * `Server` - the Faktory daemon which stores background jobs in queues to be processed by Workers.

  This package contains only the `Client` and `Worker`.

extra-source-files:
  - CHANGELOG.md
  - README.md

ghc-options: -Wall

dependencies:
  - base

default-extensions:
  - BangPatterns
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies

library:
  source-dirs: library
  dependencies:
    - aeson
    - aeson-casing
    - bytestring
    - connection
    - cryptonite
    - megaparsec
    - memory
    - network
    - random
    - safe-exceptions
    - scanner
    - text
    - time
    - unix

executables:
  faktory-example-producer:
    main: Main.hs
    source-dirs: examples/producer
    dependencies:
      - aeson
      - faktory
      - safe-exceptions

  faktory-example-consumer:
    main: Main.hs
    source-dirs: examples/consumer
    dependencies:
      - aeson
      - faktory
      - safe-exceptions

tests:
  hspec:
    main: Spec.hs
    source-dirs: tests
    ghc-options: -rtsopts -O0
    dependencies:
      - faktory
      - hspec

  readme:
    main: README.lhs
    source-dirs: .
    ghc-options: -Wall -pgmL markdown-unlit
    dependencies:
      - aeson
      - base
      - faktory
      - markdown-unlit
