---
version: 2
jobs:
  build:
    docker:
      # https://github.com/haskell-works/stack-build/blob/master/minimal/Dockerfile
      - image: quay.io/haskell_works/stack-build-minimal
      - image: contribsys/faktory:0.9.0
        name: faktory
    environment:
      STACK_ARGUMENTS: --no-terminal
    steps:
      - checkout
      - run:
          name: Digest
          command: |
            git ls-files | xargs md5sum > digest
      - restore_cache:
          keys:
            - v2-{{ .Branch }}-{{ checksum "digest" }}
            - v2-{{ .Branch }}-
            - v2-master-
      - run:
          name: Upgrade Stack
          command: stack upgrade
      - run:
          name: Dependencies
          command: make setup
      - run:
          name: Build
          command: make build
      - save_cache:
          key: v2-{{ .Branch }}-{{ checksum "digest" }}
          paths:
            - ~/.stack
            - ./.stack-work
      - run:
          name: Lint
          command: make lint
      - run:
          name: Test
          command: make test
          environment:
            FAKTORY_URL: tcp://faktory:7419
