version: 2.1

orbs:
  stack-build: pbrisbin/stack-build@4.0.0

executors:
  default:
    docker:
      - image: quay.io/haskell_works/stack-build-minimal
        environment:
          FAKTORY_URL: tcp://faktory:7419
      - image: contribsys/faktory:0.9.0
        name: faktory

defaults: &defaults
  executor: default
  install-stack: false
  upgrade-stack: true

workflows:
  commit:
    jobs:
      - stack-build/build-test-lint:
          name: "default"
          <<: *defaults
      - stack-build/build-test-lint:
          name: "ghc-8.8.2 / lts-15.3"
          stack-yaml: stack-lts-15.3.yaml
          <<: *defaults
      - stack-build/build-test-lint:
          name: "ghc-8.6.3 / lts-13.1"
          stack-yaml: stack-lts-13.1.yaml
          <<: *defaults
      - stack-build/build-test-lint:
          name: "ghc-8.4.4 / lts-12.21"
          stack-yaml: stack-lts-12.21.yaml
          <<: *defaults
      - stack-build/build-test-nightly:
          name: "nightly"
          <<: *defaults

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - stack-build/build-test-nightly:
          name: "nightly"
          <<: *defaults
