---
version: 2

references:
  stack_build: &stack_build
    docker:
      # https://github.com/haskell-works/stack-build/blob/master/minimal/Dockerfile
      - image: quay.io/haskell_works/stack-build-minimal
      - image: contribsys/faktory:0.9.0
        name: faktory
    steps:
      - checkout
      - run:
          name: Digest
          command: |
            {
              stack --version
              echo -- "$STACK_YAML/$STACK_ARGUMENTS"
            } > rdigest
            git ls-files | xargs md5sum > digest
      - restore_cache:
          keys:
            - v4-{{ .Branch }}-{{ checksum "rdigest" }}-{{ checksum "digest" }}
            - v4-{{ .Branch }}-
            - v4-master-
      - run:
          name: Upgrade Stack
          command: stack upgrade
      - run:
          name: Dependencies
          command: make setup
      - run:
          name: Build
          command: make build
      - save_cache:
          # yamllint disable-line rule:line-length
          key: v4-{{ .Branch }}-{{ checksum "rdigest" }}-{{ checksum "digest" }}
          paths:
            - ~/.stack
            - ./.stack-work
      - run:
          name: Lint
          command: make lint
      - run:
          name: Test
          command: make test
          environment:
            FAKTORY_URL: tcp://faktory:7419

jobs:
  build:
    <<: *stack_build
  build_8.4.4:
    <<: *stack_build
    environment:
      STACK_ARGUMENTS: --no-terminal
      STACK_YAML: stack-lts-12.21.yaml
  build_8.6.3:
    <<: *stack_build
    environment:
      STACK_ARGUMENTS: --no-terminal
      STACK_YAML: stack-lts-13.1.yaml
  build_8.8.2:
    <<: *stack_build
    environment:
      STACK_ARGUMENTS: --no-terminal
      STACK_YAML: stack-lts-15.3.yaml

workflows:
  version: 2
  commit:
    jobs:
      - build
      - build_8.4.4
      - build_8.6.3
      - build_8.8.2
