---
version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-11.9
      - image: contribsys/faktory
        name: faktory
    steps:
      - checkout
      - run:
          name: Digest
          command: |
            git ls-files | xargs md5sum > digest
      - restore_cache:
          keys:
            - v2-{{ .Branch }}-{{ checksum "digest" }}
            - v2-{{ .Branch }}-
            - v2-master-
      - run:
          name: Dependencies
          command: make setup
      - run:
          name: Build
          command: make build
      - save_cache:
          key: v2-{{ .Branch }}-{{ checksum "digest" }}
          paths:
            - ~/.stack
            - ./.stack-work
      - run:
          name: Lint
          command: make lint
      - run:
          name: Test
          command: make test
          environment:
            FAKTORY_URL: tcp://faktory:7419
