on:
  pull_request:
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      faktory:
        image: docker.contribsys.com/contribsys/faktory-ent:1.4.0
        credentials:
          username: ${{ secrets.FAKTORY_REGISTRY_USERNAME }}
          password: ${{ secrets.FAKTORY_REGISTRY_PASSWORD }}
        ports:
          - 7419:7419

    strategy:
      matrix:
        stack-yaml:
          - stack.yaml
          - stack-lts-17.1.yaml
          - stack-lts-15.3.yaml
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - uses: freckle/stack-cache-action@v1.0.1
      with:
        stack-yaml: ${{ matrix.stack-yaml }}
    - uses: freckle/stack-action@main
      with:
        stack-yaml: ${{ matrix.stack-yaml }}
        weeder: false
      env:
        FAKTORY_URL: tcp://localhost:7419
