name: CI

on:
  pull_request:
  push:
    branches: main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: generate
        uses: freckle/stack-action/generate-matrix@v5
    outputs:
      stack-yamls: ${{ steps.generate.outputs.stack-yamls }}

  test:
    needs: [generate]
    runs-on: ubuntu-latest
    services:
      faktory:
        image: contribsys/faktory:1.4.2
        ports:
          - 7419:7419

    strategy:
      matrix:
        stack-yaml: ${{ fromJSON(needs.generate.outputs.stack-yamls) }}
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: freckle/stack-action@v5
        with:
          stack-build-arguments-test: |
            --test-arguments="--skip Faktory.Ent"
        env:
          STACK_YAML: ${{ matrix.stack-yaml }}
          FAKTORY_URL: tcp://localhost:7419

  test-ent:
    # It must not be a Dependabot PR or fork to have access to secrets, which
    # are needed to run the enterprise image so we can test that.
    if: |
      github.actor != 'dependabot[bot]' &&
      github.event.pull_request.head.repo.full_name == github.repository
    needs: [generate]
    runs-on: ubuntu-latest
    services:
      faktory:
        image: docker.contribsys.com/contribsys/faktory-ent:1.4.0
        credentials:
          username: ${{ secrets.FAKTORY_REGISTRY_USERNAME }}
          password: ${{ secrets.FAKTORY_REGISTRY_PASSWORD }}
        ports:
          - 7419:7419

    strategy:
      matrix:
        stack-yaml: ${{ fromJSON(needs.generate.outputs.stack-yamls) }}
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: freckle/stack-action@v5
        with:
          stack-build-arguments-test: |
            --test-arguments="--match Faktory.Ent"
        env:
          STACK_YAML: ${{ matrix.stack-yaml }}
          FAKTORY_URL: tcp://localhost:7419

  hlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/hlint-setup@v2
      - uses: haskell-actions/hlint-run@v2
        with:
          fail-on: warning
