name: CI

on:
  pull_request:
  push:
    branches: main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: generate
        uses: freckle/stack-action/generate-matrix@v4
    outputs:
      stack-yamls: ${{ steps.generate.outputs.stack-yamls }}

  test:
    needs: generate
    runs-on: ubuntu-latest
    services:
      faktory:
        image: docker.contribsys.com/contribsys/faktory-ent:1.4.0
        credentials:
          username: ${{ secrets.FAKTORY_REGISTRY_USERNAME }}
          password: ${{ secrets.FAKTORY_REGISTRY_PASSWORD }}
        ports:
          - 7419:7419

    strategy:
      matrix:
        stack-yaml: ${{ fromJSON(needs.generate.outputs.stack-yamls) }}
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: freckle/stack-action@v5
        env:
          STACK_YAML: ${{ matrix.stack-yaml }}
          FAKTORY_URL: tcp://localhost:7419

  hlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/hlint-setup@v2
      - uses: haskell-actions/hlint-run@v2
        with:
          fail-on: warning
