name: CI

on:
  pull_request:
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      faktory:
        image: docker.contribsys.com/contribsys/faktory-ent:1.4.0
        credentials:
          username: ${{ secrets.FAKTORY_REGISTRY_USERNAME }}
          password: ${{ secrets.FAKTORY_REGISTRY_PASSWORD }}
        ports:
          - 7419:7419

    strategy:
      matrix:
        stack-yaml:
          - stack-nightly.yaml   # ghc-9.8
          - stack.yaml           # ghc-9.6
          - stack-lts-21.25.yaml # ghc-9.4
          - stack-lts-20.26.yaml # ghc-9.2
          - stack-lts-19.33.yaml # ghc-9.0
          - stack-lts-18.28.yaml # ghc-8.10
          - stack-lts-16.31.yaml # ghc-8.8
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - uses: freckle/stack-action@v4
        with:
          stack-yaml: ${{ matrix.stack-yaml }}
        env:
          FAKTORY_URL: tcp://localhost:7419

  hlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/hlint-setup@v2
      - uses: haskell/actions/hlint-run@v2
        with:
          fail-on: warning
